file_format: "1"
id: jorian840
name: Jorian840
url: https://github.com/krikun98/jorian840
type: board
arch: arm
features:
  - keys
outputs:
  - usb
  - ble
siblings:
  - jorian840_left
  - jorian840_right
